### ISSUE TITLE
Requirements too generic

### ISSUE THREAD

**Issue by janfait** [epfl-dlab/homepage2vec#3]
Hi,

could you please make the requirements specific (versions) and also could you maybe split them for those who do not want to use GPU/visual features - my environment doesn't really need to have a 370MB nvidia_cublas packages I expect unless I am using them.

Thanks

**Comment by tizianopiccardi** [comment]
Hi, thank you for the feedback! Yes, we'll update the requirements soon.

Also, it makes sense to have a lightweight version of the installation. We are looking into it.

**Comment by janfait** [comment]
Much appreciated. We are using your model to detect e-commerce sites and it has been a big help especially due to language agnostic capability.

**Comment by sylvainlugeon** [comment]
We updated the dependencies versions and we specified the installation for a CPU-only usage. I'm marking this issue as closed. 

Thanks for your feedback, glad to hear that homepage2vec is helpful to you!
