### ISSUE TITLE
Problems with Dataset

### ISSUE THREAD

**Issue by XnibyH** [epfl-dlab/homepage2vec#5]
Hello,
I am having difficulty aligning the URL from the "curlie_filtered.csv.gz" file, which contains the columns "url," "uid," "label," and "lang," with the HTML from the "html_content.json.gz" file, which contains the columns "uid" and "HTML."
Unfortunately, it appears to me that the "uids" between the two files do not correspond.
I hope that you will be able to provide guidance on this matter.

**Comment by sylvainlugeon** [comment]
Hi XnibyH,
We're looking into it and we'll come back shortly.

**Comment by sylvainlugeon** [comment]
Dear XnibyH,
We fixed the indexing issue in the dataset and published a new version on [Figshare](https://figshare.com/articles/dataset/Curlie_Dataset_-_Language-agnostic_Website_Embedding_and_Classification/19406693). Indeed, some files were based on two different indexing, making it impossible to align data. Now you should be able to correctly associate URLs with their HTML content. Thanks for spotting that!

**Comment by XnibyH** [comment]
Hello Sylvain, 
Thank you for addressing the indexing issue and publishing a new dataset version on Figshare. I appreciate your prompt attention to this matter and look forward to further exploring this dataset.
